nim4/api/urls.py
from django.conf.urls import url, include, re_path
from rest_framework import routers
from .serializers import BookmarksViewSet, PlaylistsViewSet, LibraryViewSet




# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'bookmarks', BookmarksViewSet)
router.register(r'playists', PlaylistsViewSet)
router.register(r'library', LibraryViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    re_path(r'^', include(router.urls)),
]

nim4/app/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView , BookmarksListView, BookmarksSearchView, PlaylistsListView, PlaylistsSearchView, FormPageView

namespace='app'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('bookmarks/', BookmarksListView.as_view(), name='bookmarks'),
    path('bookmarks/search', BookmarksSearchView.as_view(), name='searchbookmarks'),
    path('playlists/', PlaylistsListView.as_view(), name='playlists'),
    path('playlists/search', PlaylistsSearchView.as_view(), name='searchplaylists' ),
    path('hello',FormPageView.as_view(), name='hello'),
    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nim4/library/urls.py
from django.urls import path
from .views import LibraryListView, LibraryDetailView, LibrarySearchView
from django.contrib.auth.decorators import login_required, permission_required


app_name= 'library'

urlpatterns = [
    path('library', LibraryListView.as_view(), name='library'),
    path('library/<slug:slug>/', LibraryDetailView.as_view(), name='library-detail'),
    path('library/search', LibrarySearchView.as_view(), name='searchlibrary'),
]

nim4/nim4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('app.urls')),
    path('', include('library.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),

     ]
     
     
     #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    
handler404 = 'app.views.error_404_view'

nim4/app/models.py
from django.db import models


class Bookmarks(models.Model):
    title = models.CharField(max_length=128)
    link = models.URLField()
    date = models.DateField(auto_now=False, auto_now_add=False)

    # __ Show in String __
    def __str__(self):
        return self.title


class Playlists(models.Model):
    title= models.CharField( max_length=200)
    link = models.URLField()
    date = models.DateField(auto_now=False, auto_now_add=False)

    # __ Show in String __
    def __str__(self):
        return self.title


class Project(models.Model):
    title = models.CharField(max_length=80)
    body = models.TextField()
    link = models.URLField(null=True,blank=True)
    pic = models.ImageField(upload_to='portfolio/',blank=True,null=True)

    def __str__(self):
        return self.title


class ContactForm(models.Model):
    full_name = models.CharField(max_length=128)
    email = models.EmailField()
    phone = models.CharField(max_length=16, blank=True, null=True)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.email


class FileUpload(models.Model):
    title = models.CharField(max_length=128)
    fileupload = models.FileField(upload_to='fileupload/')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "fileupload/%s" % self.fileupload

nim4/library/models.py
from django.db import models


class Library(models.Model):
    title = models.CharField(max_length=128)
    slug = models.SlugField()
    date = models.DateField(auto_now_add=False, auto_now=False)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/library/{}/".format(self.slug)

nim4/app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View
from django.views.generic.list import ListView
from django.contrib import messages
from .models import Bookmarks, Playlists, Project, ContactForm
from django.utils import timezone


def error_404_view(request,exception):
    return render(request,'app/404.html')


class HomeView(TemplateView):
    template_name='app/index-v2.html'


class BookmarksListView(ListView):
    model = Bookmarks
    paginate_by = '20'
    queryset = Bookmarks.objects.all().order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class BookmarksSearchView(ListView):

    model = Bookmarks
    paginate_by = '20'
    queryset = Bookmarks.objects.all().order_by('-date')

    def get_queryset(self):
            query = self.request.GET.get('q')
            if query:
                bookmarks_list = self.model.objects.filter(title__icontains=query)
            else:
                bookmarks_list = self.model.objects.all()
            return bookmarks_list


class PlaylistsListView(ListView):
    model = Playlists
    paginate_by = '20'
    queryset = Playlists.objects.all().order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class PlaylistsSearchView(ListView):

    model = Playlists
    paginate_by = '20'
    queryset = Playlists.objects.all().order_by('-date')

    def get_queryset(self):
            query = self.request.GET.get('q')
            if query:
                playlists_list = self.model.objects.filter(title__icontains=query)
            else:
                playlists_list = self.model.objects.all()
            return playlists_list


class FormPageView(View):
    def get(self, request):
        return render(request, 'app/hello.html', {})

    def post(self, request):
        fields = ['full_name', 'email', 'phone', 'message']
        kwargs = {}

        for field in fields:
            if field not in request.POST or request.POST[field] == '':
                messages.error(request, 'Please enter {}'.format(field))
                return self.get(request)
            kwargs[field] = request.POST.get(field)
        ContactForm.objects.create(**kwargs)

        messages.success(request, 'Your message has been submitted')
        return self.get(request)

nim4/library/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.views.generic import ListView, DetailView
from .models import Library
# +++ import Utils +++
from django.utils import timezone
from django.contrib.auth.decorators import login_required



class LibraryListView(ListView):
    model = Library
    paginate_by = '20'
    queryset = Library.objects.all().order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class LibraryDetailView(DetailView):
    model = Library

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class LibrarySearchView(ListView):

    model = Library
    paginate_by = '20'
    queryset = Library.objects.all().order_by('-date')

    def get_queryset(self):
            query = self.request.GET.get('q')
            if query:
                library_list = self.model.objects.filter(title__icontains=query)
            else:
                library_list = self.model.objects.all()
            return library_list

nim4/app/templates/app/base.html
<!DOCTYPE html>
{% load static analytical %}

<html>

<head>

    <!--Import Google Icon + Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Pirata+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Pirata+One&family=VT323&family=Roboto:wght@600&display=swap" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'app/css/devicons.css' %}">


    <link type="text/css" rel="stylesheet" href="{% static 'app/css/materialize.css' %}"  >

    <link type="text/css" rel="stylesheet" href="{% static 'app/css/style.css' %}" >



    <script src="{% static 'app/js/scrollreveal.js' %}"></script>



    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

       <!-- favicons
	================================================== -->
	<link rel="icon" type="image/png" href="{% static 'app/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'app/favi/apple-icon-60x60.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'app/favi/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'app/favi/favicon-32x32.png' %}">
    <!--<link rel="manifest" href="{% static 'app/favi/manifest.json' %}">-->
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'app/favi/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- analytic -->
     {% analytical_head_top %}

    {% analytical_head_bottom %}
    <title>{% block title %}Nim4 {% endblock %}</title>

</head>

<body class="black">

<!-- PreLoader-->
{% include 'app/include/_preloader.html' %}

<!-- Navbar -->
{% include 'app/include/_nav.html' %}

<!-- Main Content -->

{% block content %}
{% endblock content %}

{% include 'app/include/_floatbtn.html' %}

<!-- Footer -->
{% block footer %}
{% include 'app/include/_footer.html' %}
{% endblock footer %}

    <!--JavaScript at end of body for optimized loading-->

    <script type="text/javascript" src="{% static 'app/js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/materialize.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/init.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/js/scroll.js' %}"></script>

    {% analytical_body_top %}

    {% analytical_body_bottom %}
</body>

</html>

nim4/app/templates/app/bookmarks_list.html
{% extends 'app/base.html' %}

{% load static %}
{% block title %}{{ block.super }} | Bookmarks {% endblock %}
{% block content %}

<main class="">

    <div class="container-v" id='main-text'>
        <div class="row ">

            <div class="col s12 m10 l6 offset-m1 offset-l3 card black hoverable">
                <!-- <h2 class="white-text">Welcome to my hood !</h2> -->

                <div class='col s6 valign-wrapper'>
                    <a href="{% url 'home' %}" class="breadcrumb valign-wrapper" id='fontgang'> Home</a>
                    <a href="{% url 'bookmarks' %}" class="breadcrumb valign-wrapper" id='fontgang'>Bookmarks</a>
                </div>
                <div class='col s6'>
                    <form action="{% url 'searchbookmarks' %}" method="get">
                        <input name="q" type="text" placeholder="🔍" class='grey-text'>
                    </form>
                </div>
                
                <div class="card-content ">
                    <br>
                    <br>
                    
                    {% if bookmarks_list %}
                    {% for book in bookmarks_list %}
                    <a href='{{ book.link }}' target="_blank">
                        <p class="grey-text"><span style="font-size: larger;" ><span id="fo">+ {{ book.title}}</span><span
                                    class='right badge' >{{book.date|date:"M Y"}}</span></p>
                    </a>
                    {% endfor %}
                    {% else %}
                    <p class='white-text'> Ops , Nothing here :(</p>
                    {% endif %}
                    <br>

                    <hr class='new'>
                    <div class="center">
                        <span class='center grey-text'>
                            {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first  </a>-
                            <a href="?page={{ page_obj.previous_page_number }}">previous  </a>-
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next - </a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>
<!-- Float Button -->


{% endblock %}

nim4/app/templates/app/bookmarks_tag.html
{% extends 'app/base.html' %}

{% load static %}
{% block title %}{{ block.super }} | Tags {% endblock %}
{% block content %}

<main class="">
    <div class="container-v" id='main-text'>
        <div class="row ">
            <div class="col s12 m6 l6 offset-m3 offset-l3 card black hoverable">

                <div class="card-content ">
                   <a href="{% url 'bookmarks' %}" class="btn-floating halfway-fab waves-effect waves-light grey darken-4 left"><i class="material-icons">arrow_back</i></a>
                    {% for book in bookmarks %}
                    <a href='{{ book.link }}' target="_blank">
                        <p class="grey-text"><span style="font-size: larger;">+ {{ book.title}}<span
                                    class='right badge'>{{book.date|date:"M Y"}}</span></p>
                    </a>


                    
                    {% endfor %}
                    <hr>

                    <div class="center">
                        <span class='center grey-text'>
                            {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

nim4/app/templates/app/include/_floatbtn.html
{% load static %}
<!-- [Floating BTN] -->
    <div class="fixed-action-btn" >
        <a class="btn-floating btn-large black">
            <i class="large material-icons blue-text">apps</i>
        </a>
        <ul>
            {% if not user.is_staff %}
            {% endif %}
            {% if user.is_staff %}
            <li><a class="btn-floating grey darken-1" href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
            {% endif %}
            <li><a class="btn-floating grey darken-2" href="{% url 'bookmarks' %}"><i class="material-icons">bookmark</i></a></li>
            <li><a class="btn-floating grey darken-3" href="{% url 'home' %}" ><i class="material-icons">home</i></a></li>
        </ul>
    </div>

nim4/app/templates/app/include/_footer.html
    <!-- [Footer] -->
    {% load static %}
    <footer class="page-footer transparent">

        <div class="footer-copyright transparent">
            <div class="container hide-on-small-and-down center">
                <h6 class="">2008-{% now 'Y' %}</h6>
            </div>
             <div class="container hide-on-med-and-up center">   <h6 class="">2008-{% now 'Y' %} </h6>
            </div>
        </div>
    </footer>

nim4/app/templates/app/include/_nav.html
{% load static %}
<!-- [NAVBAR] -->
<nav>
        <div class="nav-wrapper black">
                <a href="{% url 'home' %}" class="brand-logo"><img src="{% static 'app/img/nk.gif' %}" alt="NiM4"
                                id="logo"></a>
                <a href="#" data-target="mobile" class="sidenav-trigger"><i
                                class="material-icons blue-text">menu</i></a>
                <ul class="right hide-on-med-and-down ">
                        {% if not user.is_staff %}

                        <li><a class="white-text waves-effect waves-light" href="{% url 'bookmarks' %}" >
                                 Bookmarks</a></li>
                        <li><a class="white-text waves-effect waves-light" href="{% url 'playlists' %}" >
                                 Playlists</a></li>
                                 <li><a class="white-text waves-effect waves-light" href="{% url 'library:library' %}" >
                                        Library</a></li>
                        <li><a class="white-text waves-effect waves-light" href="{% url 'hello' %}" >
                                 Say Hello!</a></li>
                        <li><a class="tooltipped waves-effect" href="{% url 'login' %}" data-position="bottom"
                                      data-tooltip="Login"> <i class="material-icons blue-text">input</i></a></li>
                        {% else %}
                        <li><a class="white-text waves-effect waves-light" href="{% url 'library:library' %}" >
                                 Library</a></li>
                        <li><a class="white-text waves-effect waves-light" href="{% url 'bookmarks' %}" >
                                 Bookmarks</a></li>
                        <li><a class="white-text waves-effect waves-light" href="{% url 'playlists' %}" >
                                 Playlists</a></li>
                        <li><a class="white-text waves-effect waves-light" href="{% url 'hello' %}" >
                                 Say Hello!</a></li>

                        <li><a class="tooltipped waves-effect waves-light" href="{% url 'logout' %}"
                                        data-position="bottom" data-tooltip="Exit"> <i class="material-icons blue-text">power_settings_new</i></a></li>
                        {% endif %}
                </ul>
        </div>
</nav>


<!-- [MOBNAVBAR] -->
<ul class="sidenav grey darken-4 white-text" id="mobile">
        {% if not user.is_staff %}
        <li><a class="white-text" href="{% url 'home' %}">> Home</a></li>
        <li><a class="white-text" href="{% url 'bookmarks' %}">> Bookmarks</a></li>
        <li><a class="white-text" href="{% url 'playlists' %}">> Playlists</a></li>
        <li><a class="white-text" href="{% url 'library:library' %}">> Library</a></li>

         <li><a class="white-text" href="{% url 'hello' %}">> Say Hello</a></li>
        <li><a class="white-text" href="{% url 'login' %}">> Log In</a></li>
        {% else %}
        <li><a class="white-text" href="{% url 'home' %}">> Home</a></li>
        <li><a class="white-text" href="{% url 'library:library' %}">> Library</a></li>
        <li><a class="white-text" href="{% url 'bookmarks' %}">> Bookmarks</a></li>
        <li><a class="white-text" href="{% url 'playlists' %}">> Playlists</a></li>
        <li><a class="white-text" href="{% url 'hello' %}">> Say Hello</a></li>
        <li><a class="white-text" href="{% url 'logout' %}">> Log Out</a></li>
        {% endif %}


</ul>
<!-- [END NAVBAR] -->

nim4/app/templates/app/index-v2.html
<!DOCTYPE html>
{% load static analytical %}
<html lang="en" class="no-js">
	<head>
        <meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css2?family=Pirata+One&family=VT323&family=Roboto:wght@600&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="{% static 'app/css/devicons.css' %}">
         <link type="text/css" rel="stylesheet" href="{% static 'app/css/basev2.css' %}"  >
        <link type="text/css" rel="stylesheet" href="{% static 'app/css/materialize.css' %}"  >
        <link rel="icon" type="image/png" href="{% static 'app/favicon.ico' %}">
        <link rel="apple-touch-icon" sizes="60x60" href="{% static 'app/favi/apple-icon-60x60.png' %}">
        <link rel="icon" type="image/png" sizes="192x192" href="{% static 'app/favi/android-icon-192x192.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'app/favi/favicon-32x32.png' %}">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="{% static 'app/favi/ms-icon-144x144.png' %}">
        <meta name="theme-color" content="#ffffff">
        <!-- analytic -->
         {% analytical_head_top %}
        {% analytical_head_bottom %}
        <meta name="description" content="Welcome To my Hood !" />
		<meta name="keywords" content="computer,software,engineer" />
		<meta name="author" content="Nim4 k" />

		<title>Nim4</title>
		<script>document.documentElement.className="js";var supportsCssVars=function(){var e,t=document.createElement("style");return t.innerHTML="root: { --tmp-var: bold; }",document.head.appendChild(t),e=!!(window.CSS&&window.CSS.supports&&window.CSS.supports("font-weight","var(--tmp-var)")),t.parentNode.removeChild(t),e};supportsCssVars()||alert("Please view this demo in a modern browser that supports CSS Variables.");</script>
	</head>
	<body class="demo-4 black">


      <nav class="transparent">
        <div class="nav-wrapper transparent">
             <a href="{% url 'home' %}" class="brand-logo"><img src="{% static 'app/img/nk.gif' %}" alt="NiM4"
                                id="logo" style="padding-top:5px ;padding-left: 10px;max-height: 35px;"></a>
        </div>
    </nav>

		<main>
			<div class="content">
				<canvas class="scene scene--full" id="scene"></canvas>
				<div class="transparent">
					<div class="">

						<div class=" hide-on-small-and-down center">
                            <h1 class="white-text" id='fontgang'>Nima Karimi </h1>
                                <h4 class="grey-text" id='' style="padding-top: -10;">Software engineer</h4>
                        <br>
                        <br>

						</div>
						 <div class=" hide-on-med-and-up center">
						    <h3 class="white-text" id=''> Nima Karimi</h3>
           				 </div>


						<div class='col s12 center card transparent'>



                                    {% if not user.is_staff %}
                                    <a href="{% url 'library:library' %}"> <img src="{% static 'app/img/library-btn.png' %}" alt="LIBRARY"
                                    style="padding-top:5px ;"></a>
                                    <a href="{% url 'hello' %}" ><img src="{% static 'app/img/contact-btn.png' %}" alt="CONTACT"
                                    id="logo" style="padding-left:25px ;"></a><br>                                


                                <a href="{% url 'playlists' %}"><img src="{% static 'app/img/playlist-btn.png' %}" alt="PLAYLIST"
                                style="padding-top:5px ;"></a>
                                <a href="{% url 'bookmarks' %}"><img src="{% static 'app/img/bookmarks-btn.png' %}" alt="BOOKMARKS"
                                style="padding-left:25px ;"></a><br>



                                <a href="https://www.linkedin.com/in/nim4" target="_blank"><img src="{% static 'app/img/linkedin-btn.png' %}" alt="Linkedin"
                                    style="padding-top:5px ;" ></a>
                                   <a href="https://github.com/nim444" target="_blank"><img src="{% static 'app/img/github-btn.png' %}" alt="GITHUB"
                                    style="padding-left:25px ;"></a><br>

                                    {% else %}
                                    <a class="btn grey darken-4 white-text waves-effect waves-light" href="{% url 'library:library' %}" >
                                             > Library</a>
                                    <a class="btn grey darken-4 white-text waves-effect waves-light" href="{% url 'bookmarks' %}" >
                                             > Bookmarks</a>
                                    <a class="btn grey darken-4 white-text waves-effect waves-light" href="{% url 'playlists' %}" >
                                             > Playlists</a>
                                    {% endif %}

						</div>

                        



					</div>
				</div>
			</div>
		</main>


      <!-- [Floating BTN] -->
    <div class="fixed-action-btn" >
        <a class="btn-floating btn-large black" href="{% url 'hello' %}">
            <i class="large material-icons blue-text">question_answer</i>
        </a>
        {% if not user.is_staff %}
        <a class="btn-floating btn-large black" href="{% url 'login' %}">
            <i class="large material-icons blue-text">input</i>
        </a>
        {% else %}
        <a class="btn-floating btn-large black" href="{% url 'logout' %}">
            <i class="large material-icons blue-text">power_settings_new</i>
        </a>
        {% endif %}

    </div>



    <footer class="page-footer transparent">
        <div class="footer-copyright transparent">
            <div class="container hide-on-small-and-down center">
                <h4><i class="devicons devicons-python"></i>
                <i class="devicons devicons-django"></i></h4>
                <h6 class="">© Nima K. 2008 - {% now 'Y' %} </h6>


            </div>

             <div class="container hide-on-med-and-up center">   <h6 class="">© Nima K. 2008 - {% now 'Y' %} </h6>
            </div>
        </div>
    </footer>

        <script type="text/javascript" src="{% static 'app/js/initv2.js' %}"></script>
        <script type="text/javascript" src="{% static 'app/js/three.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'app/js/TweenMax.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'app/js/perlin.js' %}"></script>
        <script type="text/javascript" src="{% static 'app/js/indexv2.js' %}"></script>
	</body>
</html>

nim4/library/templates/library/library_detail.html
{% extends 'app/base.html' %}

{% load static %}
{% block title %}{{ block.super }} | Library {% endblock %}
{% block content %}

<main class="">

    <div class="container-v" id='main-text'>
        <div class="row ">

            <div class="col s12 m10 l8 offset-m1 offset-l2 card black hoverable">

                <div class='col s10 valign-wrapper'>

                    <a href="" class="breadcrumb valign-wrapper" id='fontgang'>{{ object.title}}</a>
                </div>
                <div class='col s2'>
                    <a class="btn-floating btn-small right" href="{% url 'library:library' %}">   <i class="material-icons">arrow_back</i></a>
                </div>

                <div class="card-content ">
                    <br>
                    <br>

                    {% if object %}



                    <br>
                    <div class="white-text" id="fontt">
                         {{ object.body|safe }}
                    </div>




                    {% else %}
                    <p class='white-text'> Ops , Nothing here :(</p>
                    {% endif %}
                    <br>




                    <hr class='new'>
                    <div class="center">
                        <span class='center grey-text'>

                            <span class='' >Publish at {{object.date|date:"M Y"}}</span>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>
{% endblock %}

nim4/library/templates/library/library_list.html
{% extends 'app/base.html' %}

{% load static %}
{% block title %}{{ block.super }} | Library {% endblock %}
{% block content %}

<main class="">

    <div class="container-v" id='main-text'>
        <div class="row ">

            <div class="col s12 m10 l6 offset-m1 offset-l3 card black hoverable">
                <!-- <h2 class="white-text">Welcome to my hood !</h2> -->

                <div class='col s6 valign-wrapper'>
                    <a href="{% url 'home' %}" class="breadcrumb valign-wrapper" id='fontgang'> Home</a>
                    <a href="{% url 'library:library' %}" class="breadcrumb valign-wrapper" id='fontgang'>Library</a>
                </div>
                <div class='col s6'>
                    <form action="{% url 'library:searchlibrary' %}" method="get">
                        <input name="q" type="text" placeholder="🔍" class='grey-text'>
                    </form>
                </div>

                <div class="card-content ">
                    <br>
                    <br>

                    {% if library_list %}
                    {% for library in library_list %}
                    <a href='{{ library.get_absolute_url }}' target="_top">
                        <p class="grey-text"><span style="font-size: larger;" ><span id="fo">+ {{ library.title}}</span><span
                                    class='right badge' >{{library.date|date:"M Y"}}</span></p>
                    </a>
                    {% endfor %}
                    {% else %}
                    <p class='white-text'> Ops , Nothing here :(</p>
                    {% endif %}
                    <br>

                    <!--
                    <span class='grey-text'>Tags:</span>

                    {% for tag in tags %}
                    <a class="" href="{% url 'tagged' tag.slug %}">{{ tag.name }}</a>

                    {% empty %}
                    No Tags :)
                    {% endfor %}
                    -->

                    <hr class='new'>
                    <div class="center">
                        <span class='center grey-text'>
                            {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first  </a>-
                            <a href="?page={{ page_obj.previous_page_number }}">previous  </a>-
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next - </a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>
<!-- Float Button -->
{% include 'app/include/_floatbtn.html' %}

{% endblock %}